version: '3'
services:
  log_emitter:
    build:
      context: .
    volumes:
      - named-pipe-volume:/tmp/namedPipes
      - ./code:/usr/src/app/code
    command: python /usr/src/app/code/log_emmiter.py

  # connect the log_emitter container's /tmp/namedPipes dir
  # into log_collector container's /tmp/cooler dir
  log_collector:
    build:
      context: .
    volumes:
      - named-pipe-volume:/tmp/namedPipes
      - ./code:/usr/src/app/code
    command: python /usr/src/app/code/log_collector.py

  timescale_db:
    image: timescale/timescaledb:latest-pg10
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: hey_NSA
    ports:
      - 5432:5432

volumes:
  named-pipe-volume: