version: '3'
services:
  metrics_emitter:
    build:
      context: .
      args:
        - IMAGE_VERSION=${IMAGE_VERSION:-2.7}
    volumes:
      - named-pipe-volume:/tmp/namedPipes
      - ./code:/usr/src/app/code
    command: python /usr/src/app/code/metrics_emmiter.py

  # connect the metrics_emitter container's /tmp/namedPipes dir
  # into metrics_collector container's /tmp/cooler dir
  metrics_collector:
    build:
      context: .
      args:
        - IMAGE_VERSION=${IMAGE_VERSION:-3.7}
    volumes:
      - named-pipe-volume:/tmp/namedPipes
      - ./code:/usr/src/app/code
    command: python /usr/src/app/code/metrics_collector.py

volumes:
  named-pipe-volume: